---
name: 🐛 Bug Report
description: Report a reproducible bug in the current release of pynetbox
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: >
        **NOTE:** This form is only for reporting _reproducible bugs_ in a current py-jelastic release.
  - type: input
    attributes:
      label: py-jelastic version
      description: What version of py-jelastic are you currently running?
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Jelastic version
      description: What version of Jelastic are you currently running?
      placeholder: v8.4.2
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Python version
      description: What version of Python are you currently running?
      options:
        - "3.10"
        - "3.11"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >
        Please provide a minimal working example to demonstrate the bug. Ensure that your example is as 
        concise as possible while adequately illustrating the issue. For example:
        ```python
        >>> from src.jelastic import Jelastic
        >>> jl = Jelastic('https://api.example.com', token='my-token')
        
        ```
        Note: **do not utilize the demo instance** for replicating suspected bugs, 
        as its data is subject to change or removal at any time.
        
        _Please refrain from including any confidential or sensitive 
        information in your example._
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The script should execute without raising any errors or exceptions
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed Behavior
      description: What happened instead?
      placeholder: A TypeError exception was raised
    validations:
      required: true
