name: Sync Labels

on:
  push:
    branches:
      - master
    paths:
      - ".github/**"

jobs:
  labels:
    runs-on: ubuntu-latest
    name: Sync labels
    steps:
      - name: sync labels
        uses: abhi1693/labels@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
