name: Py3 Test

on:
  pull_request: { }
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11" ]
    env:
      JELASTIC_TOKEN: ${{ secrets.JELASTIC_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dev requirements
        run: |
          pip install -e .
          pip install coverage pytest

      - name: Run Tests
        run: coverage run -m pytest --tb=short -vvv

      - name: Show Coverage
        run: coverage report --omit="tests/*"
